# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# mouse control
set -g mouse on

# Change color of bar
# set status-utf8 on
# set utf8 on

set -g default-terminal "screen-256color"
set -g status-bg cyan
set -g status-fg black

set -g pane-border-style fg=green
set -g pane-active-border-style bg=default,fg=red

# set-option -g pane-border-lines double
set-option -g pane-border-indicators both
# set -g status-style bg=default
