[colors.primary]
background = '#242829'
foreground = '#dcd7d7'

[colors.normal]
black   = '#242829'
red     = '#df2683'
green   = '#13868c'
yellow  = '#fcfcdf'
blue    = '#1a86b9'
magenta = '#bc7fd2'
cyan    = '#7cc7d6'
white   = '#4a4b4b'

[colors.bright]
black   = '#7b8b99'
red     = '#df2683'
green   = '#13868c'
yellow  = '#fcfcdf'
blue    = '#1a86b9'
magenta = '#bc7fd2'
cyan    = '#7cc7d6'
white   = '#dcd7d7'


# white 220 215 215
# blue 229 233 249
# darkblue 19 134 140
# lightblue 124 199 214
# pink 223 38 131
# purple 188 127 210
# grey 74 75 75

# emphasis_0 223 38 131
# emphasis_1 188 127 210
# emphasis_2 229 233 249
# emphasis_3 124 199 214
