#!/usr/bin/env perl

use strict;
use warnings;

sub get_interface {
    my $ip_route = `ip route`;
    if ($ip_route =~ m/^default via \S+ dev (\S+)/m) {
        return $1;
    }
    die "Interface not found";
}

sub get_device_data {
    my $interface = shift;
    die "Interface not found" unless $interface;

    my $dev_data = `cat /proc/net/dev`;
    if ($dev_data =~ m/^\s*$interface:\s*(.*)/m) {
        return $1;
    }
    die "No data for $interface";
}

sub extract_bytes {
    my $data = shift;
    die "No data found" unless $data;

    my @stats = split(/\s+/, $data);
    if (defined $stats[0] && defined $stats[8]) {
        return (
            "down" => $stats[0] * 8,
            "up"   => $stats[8] * 8,
        );
    }
    die "Can't extract upload data";
}

sub take_average {
    my $interface = get_interface();
    my $iter = 5;

    my $avg_down;
    my $avg_up;
    for my $t (1..$iter) {
        my $dev_data_t0 = get_device_data($interface);
        my %bytes_t0 = extract_bytes($dev_data_t0);
        $_ = `sleep 0.2`;
        my $dev_data_t1 = get_device_data($interface);
        my %bytes_t1 = extract_bytes($dev_data_t1);

        my $delta_down = ($bytes_t1{"down"} - $bytes_t0{"down"}) / 1_000_000;
        my $delta_up = ($bytes_t1{"up"} - $bytes_t0{"up"}) / 1_000_000;
        $avg_down += $delta_down / $iter;
        $avg_up += $delta_up / $iter;
    }
    return (
        "down" => $avg_down / 0.2,
        "up" => $avg_up / 0.2,
    );
}

sub load_colors {
    my $file = "$ENV{HOME}/Dev/dotfiles/.colors";
    my %colors;
    open(my $fh, '<', $file) or die "Could not open $file: $!";
    while (<$fh>) {
        chomp;
        my ($key, $val) = split(/=/);
        $colors{$key} = $val;
    }
    close($fh);
    return %colors;
}

my $label = $ENV{label} // "uwu";
my %avg = take_average(10);
# printf "The cost is \$%6.2f\n",499;

my %c = load_colors();

printf "<span color='$c{fg1}'>%.2f|%.2f</span>\n", $avg{'down'} / 1, $avg{'up'} / 1;
