#!/usr/bin/env perl

# Made by ~ PiaCOS ~
# This script gives you the battery percentage in the pango markup format.
# It needs `acpi` installed on your device.

use strict;
use warnings;
use POSIX qw/floor/;

my $label = $ENV{LABEL} // "";
my $acpi = `acpi`;

my ($percent) = $acpi =~ /,\s(\b\d+)%/;
my ($state) = $acpi =~ /\s(\b[A-Z][a-z]+),/;

sub load_colors {
    my $file = "$ENV{HOME}/Dev/dotfiles/.colors";
    my %colors;
    open(my $fh, '<', $file) or die "Could not open $file: $!";
    while (<$fh>) {
        chomp;
        my ($key, $val) = split(/=/);
        $colors{$key} = $val;
    }
    close($fh);
    return %colors;
}

sub get_color {
  my $p = shift;
  my %c = load_colors;
  my $ratio = floor($p / 10);
  my %colors = (
    1 => $c{danger},
    2 => $c{danger},
    3 => $c{warning},
    4 => $c{alert},
    # 5 => "#FFCC00",
    # 6 => "#FFFF00",
    # 7 => "#FFFF33",
    # 8 => "#FFFF66",
  );
  return $colors{$ratio} // "#FFFFFF";
}

sub to_pango {
  my $p = shift;
  my $s = shift;

  my $color = get_color($p);

  if ($s eq "Charging") {
    return "$label<span color='$color'>+$p%</span>";
  }
  elsif ($p < 10) {
    return "$label<span foreground='#FF0000'>$p%!</span>";
  }
  elsif ($s eq "Full") {
    return "$label<span color='$color'>FULL</span>";
  }
  else {
    return "$label<span color='$color'>$p%</span>";
  }

}

my $pango = to_pango($percent, $state);
print "$pango\n";
print "$pango\n";

