#!/usr/bin/env perl

use strict;
use warnings;

# ::|> ping 1.1.1.1 -c 2 -W 1                                                                                 09:47
# PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
# 64 bytes from 1.1.1.1: icmp_seq=1 ttl=57 time=6.79 ms
# 64 bytes from 1.1.1.1: icmp_seq=2 ttl=57 time=18.5 ms

# --- 1.1.1.1 ping statistics ---
# 2 packets transmitted, 2 received, 0% packet loss, time 1002ms
# rtt min/avg/max/mdev = 6.785/12.641/18.498/5.856 ms

my $ping_output = `ping 1.1.1.1 -c 10 -W 1 -i 0.1`;

if ($ping_output =~ m/^rtt min\/avg\/max\/mdev \= .+\/(.+)\/.+\/.+ ms$/m) {
    my $ping = $1;
    printf "<span>%.2f</span>\n", $ping;
} else {
    my $face = "°-°";
    printf "<span>$face</span>\n";
}
