#!/usr/bin/env perl

use strict;
use warnings;

my $dbs = `psql -U postgres -t -A -c "SELECT datname FROM pg_database WHERE datistemplate = false;"`;

open(my $pipe, '|-', "fzf --header=':: Choose a database ::'") or die "bleep bloop: $!";
print $pipe $dbs;
close($pipe);
