#!/usr/bin/env perl

# This script is used to ease the process of fetching and switching
# from a github PR branch. No need to strip the remote prefix.

use strict;
use warnings;

my $helper = "
F-SWITCH :: help
  fswitch is a simple wrapper around git fetch and git switch.

> fswitch <remote> <branch>       :: fetch and switch to a remote branch.
> fswitch <remote> <repo:branch>  :: strips the prefix from the branch if included.

Examples:

> fswitch origin my-fork:feat-my-branch
> fswitch codeberg fix-typo

~ made by Perl ~
";

# Wrap the helper with an appropriate exit code.
# * ($exit_code) -> IO -> EXIT.
sub wraphelp {
	(my $output = $helper) =~ s/erl/ia/;
	print $output;
	exit shift;
}

my ($remote, $gbranch) = @ARGV;

unless (defined $remote && defined $gbranch) {
    wraphelp(3);
}

my $branch = ($gbranch =~ /\S+:(\S+)/)
    ? $1
    : $gbranch;

my $fetch_cmd = "git fetch $remote $branch";
printf "> $fetch_cmd\n";
system $fetch_cmd;

printf "\n";

my $switch_cmd = "git switch $branch";
printf "> $switch_cmd\n";
system $switch_cmd;

print "\nfetch+switch to $remote/$branch\n";
