#!/usr/bin/env bash
set -e

DOTFILES_DIR="$HOME/Dev/dotfiles"
CONFIG_DIR="$HOME/.config"

echo "Setting up symbolic links..."

# '-sfn': s=symlink, f=force (overwrite), n=no-dereference (safer for directories)

# ----------------- .config/ Directories -----------------
ln -sfn $DOTFILES_DIR/fish $CONFIG_DIR/fish
ln -sfn $DOTFILES_DIR/helix $CONFIG_DIR/helix
ln -sfn $DOTFILES_DIR/i3 $CONFIG_DIR/i3
ln -sfn $DOTFILES_DIR/wezterm $CONFIG_DIR/wezterm
ln -sfn $DOTFILES_DIR/zellij $CONFIG_DIR/zellij

# ---------------------- Executables ---------------------
ln -sf $DOTFILES_DIR/scripts/reset_ssh_agent $HOME/bin/reset_ssh_agent

echo "Symbolic links are ready!!"
