default:
    @just --list --unsorted

# -------- Variables --------
BIN := "community/odoo-bin"
PORT := "8869"
DB := "default_db"
DEV := "xml,qweb"

COMMUNITY_ADDONS := "community/addons"
ENTERPRISE_ADDONS := "community/addons,enterprise"

SELECTED_MODULES := "project,web_studio,contact,api_doc,hr,crm"
RANDOM_MODULES := "project,web_studio,contact,api_doc,hr,crm,sale_management,stock,purchase,accountant,point_of_sale,mrp,mass_mailing,documents,calendar,mysubscription"

# -------- DB Config -------- #
DB_ARGS := "--db_host=localhost --db_user=odoo --db_password=odoo"

# -------- PSQL Recipes -------- #

# Echo all dbs name
dbs:
    @psql -U postgres -c "\l" \
        | rg -o "^\s(\S+)\s*\|" -r '$1' \
        | rg -v "^(template\d|postgres)$"

# Pipe all dbs name into fzf
fzf-dbs:
    @psql -U postgres -c "\l" \
        | rg -o "^\s(\S+)\s*\|" -r '$1' \
        | rg -v "^(template\d|postgres)$" \
        | fzf -m --header ":: Choose a database ::"

# Drop selected dbs
dropdd:
    @psql -U postgres -c "\l" \
        | rg -o "^\s(\S+)\s*\|" -r '$1' \
        | rg -v "^(template\d|postgres)$" \
        | fzf -m --header ":: Choose a database ::" \
        | iter "dropdb -h localhost -U odoo {}" -d

# List all databases
list-db:
    psql -U postgres -c "\l"

# List all users
list-user:
    psql -U postgres -c "\du"

# Add pg_vector to a db (for AI stuff)
addext_pgvector DB='$(just fzf-dbs)':
    # Might be necessary to:
    # - install pgvector: `yay -S pgvector`
    # - install pgvector in env: `uv pip install pgvector`
    psql {{DB}} -U postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"

# Print selected modules
echo-selected:
    @echo {{SELECTED_MODULES}}

# Print random modules
echo-random:
    @echo {{RANDOM_MODULES}}


# -------- ODOO Recipes :: Runners -------- #

# Run community Odoo
run:
    uv run {{BIN}} --addons-path={{COMMUNITY_ADDONS}} --dev={{DEV}} {{DB_ARGS}} \
        --http-port={{PORT}}

# Run enterprise Odoo
run-e:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} {{DB_ARGS}} \
        --http-port={{PORT}}

# Run community Odoo with -d DB
drun DB='$(just fzf-dbs)':
    uv run {{BIN}} --addons-path={{COMMUNITY_ADDONS}} --dev={{DEV}} {{DB_ARGS}} \
        --http-port={{PORT}} \
        -d {{DB}}

# Run enterprise Odoo with -d DB
drun-e DB='$(just fzf-dbs)':
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} {{DB_ARGS}} \
        --http-port={{PORT}} \
        -d {{DB}}


# -------- ODOO Recipes :: Installers -------- #

# Install specific modules (eg: `just install project,crm`)
install modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{modules}} \
        --stop-after-init

# Initialize a db with demo data and specific modules (eg: `just demo project,crm`)
install-demo modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{modules}} \
        --with-demo \
        --stop-after-init

# Install modules from SELECTED
install-selected modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{SELECTED_MODULES}} \
        --stop-after-init

# Install modules from SELECTED with demo data
install-selected-demo modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{SELECTED_MODULES}} \
        --with-demo \
        --stop-after-init

# Install modules from RANDOM
install-random modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{RANDOM_MODULES}} \
        --stop-after-init

# Install modules from RANDOM with demo data
install-random-demo modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{RANDOM_MODULES}} \
        --with-demo \
        --stop-after-init


# -------- ODOO Recipes :: Specials -------- #

# Open Odoo shell
shell DB='$(just fzf-dbs)':
    uv run {{BIN}} shell --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} {{DB_ARGS}}

# Run tests for a specific module (e.g., `just test /account`, `just test :TestApiDoc`)
test modules_to_install test_tags DB='$(just fzf-dbs)':
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{modules_to_install}} -u {{modules_to_install}} \
        --test-tags {{test_tags}} \
        --stop-after-init

# Run tests for a specific module (e.g., `just test /account`, `just test :TestApiDoc`)
test_porcelain modules_to_install test_tags DB='$(just fzf-dbs)':
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} {{DB_ARGS}} \
        -d {{DB}} \
        -i {{modules_to_install}} -u {{modules_to_install}} \
        --test-tags {{test_tags}} \
        --stop-after-init \
        --log-level warn


# -------- TASK Recipes -------- #

# owl3 migration
o-owl3-migrate:
    uv run {{BIN}} upgrade_code --script owl3-migration.py --addons-path={{ENTERPRISE_ADDONS}}

# My Subscription Task quick setup
o-mysubscription:
    just demo crm,sale_manegement,hr,contacts,mysubscription mysub_demo_db
    just run-e

# Studio reorder quick setup
o-studio-reorder:
    just install web_studio,hr studio_reorder_db
    just drun-e studio_reorder_db

# Studio reorder quick setup whole test suite
o-test-studio-reorder:
    just install web_studio,hr studio_reorder_db
    just test_porcelain /web_studio studio_reorder_db

# Add followers subtype
o-mail-stuff:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d default_db \
        -i mail,base_automation,sale_management,test_mail \
        -u mail,base_automation,sale_management,test_mail \
        --with-demo

# Revert count in grouped list
o-list-count:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d list_group_db \
        -i hr,planning,contacts,project \
        -u hr,planning,contacts,project \
        --with-demo

# Try out Accountant empty group impl
o-empty-group:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d empty_group_db \
        -i accountant,project,planning \
        -u accountant,project,planning \
        --with-demo
