default:
    @just --list --unsorted

# -------- Variables --------
BIN := "community/odoo-bin"
PORT := "8869"
DB := "default_db"
DEV := "xml,qweb"

COMMUNITY_ADDONS := "community/addons"
ENTERPRISE_ADDONS := "community/addons,enterprise"

SELECTED_MODULES := "project,web_studio,contact,api_doc,hr,crm,mysubscription"
RANDOM_MODULES := "project,web_studio,contact,api_doc,hr,crm,sale_management,stock,purchase,accountant,point_of_sale,mrp,mass_mailing,documents,calendar,mysubscription"

# -------- DB Config -------- #
DB_ARGS := "--db_host=localhost --db_user=odoo --db_password=odoo"

# -------- PSQL Recipes -------- #

# Drop default_db
dropdd DB='$(dbs)':
    # dropdb -h localhost -U odoo {{DB}}
    iter "dropdb -h localhost -U odoo {}" {{DB}} -d

# List all databases
list-db:
    psql -U postgres -c "\l"

# List all users
list-user:
    psql -U postgres -c "\du"

# Add pg_vector to a db (for AI stuff)
addext_pgvector DB='$(dbs)':
    # Might be necessary to:
    # - install pgvector: `yay -S pgvector`
    # - install pgvector in env: `uv pip install pgvector`
    psql {{DB}} -U postgres -c "CREATE EXTENSION IF NOT EXISTS vector;"

# Print selected modules
echo-selected:
    @echo {{SELECTED_MODULES}}

# Print random modules
echo-random:
    @echo {{RANDOM_MODULES}}

# -------- ODOO Recipes -------- #

# Run community Odoo
run:
    uv run {{BIN}} --addons-path={{COMMUNITY_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}}

# Run enterprise Odoo
run-e:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}}

# Run community Odoo with -d DB
drun DB=DB:
    uv run {{BIN}} --addons-path={{COMMUNITY_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}}

# Run enterprise Odoo with -d DB
drun-e DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}}

# Install specific modules (eg: `just install project,crm`)
install modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} -i {{modules}} {{DB_ARGS}} --stop-after-init

# Initialize a db with demo data and specific modules (eg: `just demo project,crm`)
demo modules DB=DB:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} -i {{modules}} --with-demo {{DB_ARGS}} --stop-after-init

# Open Odoo shell
shell DB=DB:
    uv run {{BIN}} shell --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} {{DB_ARGS}}

# Run tests for a specific module (e.g., `just test /account`, `just test :TestApiDoc`)
test module DB='$(dbs)':
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} --test-tags {{module}} {{DB_ARGS}} --stop-after-init

# Run tests for a specific module (e.g., `just test /account`, `just test :TestApiDoc`)
test_porcelain module DB='$(dbs)':
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} -d {{DB}} --test-tags {{module}} {{DB_ARGS}} --stop-after-init --log-level warn


# -------- QUICK Recipes -------- #

# Run a quick db with modules in enterprise
select:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}} -i {{SELECTED_MODULES}}

# Run a quick db with modules in enterprise with demo data
select-demo:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}} -i {{SELECTED_MODULES}} --with-demo

# Run a quick db with LOTS of modules in enterprise
random:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}} -i {{RANDOM_MODULES}}

# Run a quick db with LOTS of modules in enterprise with demo data
random-demo:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} -d {{DB}} {{DB_ARGS}} -i {{RANDOM_MODULES}} --with-demo


# -------- TASK Recipes -------- #

# owl3 migration
o-owl3-migrate:
    uv run {{BIN}} upgrade_code --script owl3-migration.py --addons-path={{ENTERPRISE_ADDONS}}

# My Subscription Task quick setup
o-mysubscription:
    just demo crm,sale_manegement,hr,contacts,mysubscription mysub_demo_db
    just run-e

# Studio reorder quick setup
o-studio-reorder:
    just install web_studio,hr studio_reorder_db
    just drun-e studio_reorder_db

# Studio reorder quick setup whole test suite
o-test-studio-reorder:
    just install web_studio,hr studio_reorder_db
    just test_porcelain /web_studio studio_reorder_db

# Add followers subtype
o-mail-stuff:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d default_db \
        -i mail,base_automation,sale_management,test_mail \
        -u mail,base_automation,sale_management,test_mail \
        --with-demo

# Revert count in grouped list
o-list-count:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d list_group_db \
        -i hr,planning,contacts,project \
        -u hr,planning,contacts,project \
        --with-demo

# Try out Accountant empty group impl
o-empty-group:
    uv run {{BIN}} --addons-path={{ENTERPRISE_ADDONS}} --dev={{DEV}} --http-port={{PORT}} {{DB_ARGS}} \
        -d empty_group_db \
        -i accountant,project,planning \
        -u accountant,project,planning \
        --with-demo
